environments:
  default:
    values:
      - ./envs/default/config.yaml
      - ./envs/default/topics.yaml

  templated-environment: &templated-environment
    values:
      - git::https://{{ env "UNITY_HELMFILE_USER" }}:{{ env "UNITY_HELMFILE_TOKEN" }}@gitlab.com/williamhillplc/platform-engineering/unity/pipelines/unity-helmfile@envs/default/config.yaml?ref=master
      - git::https://{{ env "UNITY_HELMFILE_USER" }}:{{ env "UNITY_HELMFILE_TOKEN" }}@gitlab.com/williamhillplc/platform-engineering/unity/pipelines/unity-helmfile@envs/{{ .Environment.Name }}/config.yaml?ref=master
      - git::https://{{ env "UNITY_HELMFILE_USER" }}:{{ env "UNITY_HELMFILE_TOKEN" }}@gitlab.com/williamhillplc/platform-engineering/unity/pipelines/unity-helmfile@envs/default/universes.yaml?ref=master
      - git::https://{{ env "UNITY_HELMFILE_USER" }}:{{ env "UNITY_HELMFILE_TOKEN" }}@gitlab.com/williamhillplc/platform-engineering/unity/pipelines/unity-helmfile@envs/{{ .Environment.Name }}/universes.yaml?ref=master
      - ./envs/default/config.yaml
      - ./envs/default/topics.yaml
      - ./envs/{{ .Environment.Name }}/config.yaml
      - ./envs/{{ .Environment.Name }}/topics.yaml

  uat:
    <<: *templated-environment

  usd:
    <<: *templated-environment

  sit:
    <<: *templated-environment

  mtt-sit:
    <<: *templated-environment

  oat:
    <<: *templated-environment

  prod:
    <<: *templated-environment

---

{{ readFile "./helmfile-templates.yaml" }}

releases:
  - name: permissions-kafka-topics
    <<: *generic
    version: 0.0.0-develop
    chart: 'nexus/be-kafka-topics-service'
    labels:
      slack_url_var: UNITY_TEAM_D_SLACK_HOOK_URL
    { { - with (.Values | getOrNil "permissions-kafka-topics" | getOrNil "values") } }
    values:
      - { { - toYaml . | nindent 8 } }
    { { - end } }
  - name: permissions
    installed: {{ .Values | getOrNil "permissions.installed" | default "false" }}
    <<: *generic
    version: '{{ env "RELEASE_VERSION" | default (.Values | getOrNil "permissions-ep.version") | default "0.0.0-develop" | replace "/" "-" | lower }}'
    chart: 'nexus/permissions'
    labels:
      project: unity
      slack_url_var: UNITY_TEAM_D_SLACK_HOOK_URL
    {{- with (.Values | getOrNil "permissions-ep" | getOrNil "values") }}
    values:
      - {{- toYaml . | nindent 8 }}
    {{- end}}
