version: "3.9"
services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
      image: wurstmeister/kafka:2.13-2.8.1
      hostname: broker
      container_name: broker
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
        KAFKA_ADVERTISED_LISTENERS: INSIDE://broker:29092,OUTSIDE://localhost:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_CREATE_TOPICS: "exclusion_events_v1:1:1,permission_facet_events_v1:1:1,player_events_v4:1:1,dormancy_events_v1:1:1"

  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:29092
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: GET,POST,PUT,OPTIONS
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"

  schema-registry-ui:
    image: landoop/schema-registry-ui
    ports:
      - "8000:8000"
    environment:
      SCHEMAREGISTRY_URL: http://localhost:8081

  kiwi:
    image: dmwood/kiwi
    ports:
      - "8181:8080"
    environment:
      KAFKA_BASE_CLIENT_BOOTSTRAPSERVERS: broker:29092

