newrelic:
    licenceKeyBase64: ENC[AES256_GCM,data:uXDFBQIlkgnXE9Akqt7/QNgR9DWnytkVLap59TWZShHuvBDhTeSs2Lkr/51Tw1jTk/xUlTw2rl8=,iv:AMJdfYEZ1I2111xj4DHQo/f6S/gBRh8HKVt4IxZWB3M=,tag:AZCkSuoYSGFiO26iEgU4xA==,type:str]
    insightsKeyBase64: ENC[AES256_GCM,data:SrqptIuZai0Ia03IdELsm+uVl+oMHiTLpu5Fg1uYi/xdGD4Qi3P4+dMJzA7cJZcUdGoeEDbE3KhzfFA218SPrHSZj4RVD3jf,iv:cZKy7vebFo4ql1MkOwfViOSwSkzsJSQh6YZuw2oerpE=,tag:1wDfi9NcIEvvpAqWC8WoWQ==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:155749033528:alias/applications
        created_at: '2022-06-16T21:49:44Z'
        enc: AQICAHit2xL1WT5N5UccNgfTs2/Oqtf+cVc3oRjsvHzJrfIrFQHZbidBLs9sLcbrVFZLncx1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZJP95LXftYc9QHuvAgEQgDtQCwG67toXAy+9DJvQzyexe4CI+PYAdhUyKMgvfMncGklQt+rJKiwVL6Slce0W0BcfRdWblEFGlMYDZg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-06-16T21:49:44Z'
    mac: ENC[AES256_GCM,data:2CMlrMc6oG4wix5fGdfIuTDL9oQstLm6lWvO0k7LdS4MP3dhOrGVxBbWCztO03S7+MSfgVMFbsEEqBdy93Tic8eoekuo8yXM6wU3brCVT2Uj0gUhUDSVdH+K6DGng3cLvxmj+XCdFtjKAGNyvLTLYKZk+ZFaep3J9I3SrLK8UtY=,iv:oUBEoCYwm8v5CuXAiZSpuFFgu1431u3Mij5BglPLAGk=,tag:TLZKScadCuUj+OK1pvvz9w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
