environment: uat
namespace: uat
host: uat.unity.aws-eu-west-1.dev.williamhill.plc
kafka:
  kafka_servers: ref+awsssm:///uat/msk/unity-uat-msk-uat/brokers_plaintext_connection_string?region=eu-west-1
  schema_registry: http://cp-schema-registry:8081
  serviceentry: true
  zookeeper_servers: ref+awsssm:///uat/msk/unity-uat-msk-uat/zookeeper_plaintext_connection_string?region=eu-west-1
hpa:
  enabled: true
minReplicas: 1
maxReplicas: 2
permissions-ep:
  values:
    base:
      services:
        permissions-ep:
          enabled: true
          envVars:
            KAFKA_SERVERS: ref+awsssm:///uat/msk/unity-uat-msk-uat/brokers_plaintext_connection_string?region=eu-west-1
            ZOOKEEPER_SERVERS: ref+awsssm:///uat/msk/unity-uat-msk-uat/zookeeper_plaintext_connection_string?region=eu-west-1
            SCHEMA_REGISTRY_URL: http://cp-schema-registry:8081
