kafka:
  kafka_servers: kafka-service:9092
  schema_registry: http://schema-registry-service:8081
  serviceentry: true
  zookeeper_servers: zookeeper-service:2181
permissions:
  values:
    base:
      services:
        permissions-ep:
          enabled: true
