environment: sit
namespace: sit
host: sit.unity.aws-eu-west-1.dev.williamhill.plc
kafka:
  kafka_servers: ref+awsssm:///sit-new/msk/unity-sit-new-msk-sit-new/brokers_plaintext_connection_string?region=eu-west-1
  schema_registry: http://cp-schema-registry:8081
  serviceentry: true
  zookeeper_servers: ref+awsssm:///sit-new/msk/unity-sit-new-msk-sit-new/zookeeper_plaintext_connection_string?region=eu-west-1
hpa:
  enabled: true
minReplicas: 1
maxReplicas: 2
permissions:
  values:
    base:
      services:
        permissions-ep:
          enabled: true
          envVars:
            KAFKA_INPUT_TOPICS.0: exclusion_events_v1
            KAFKA_INPUT_TOPICS.1: player_events_v4
            KAFKA_INPUT_TOPICS.2: payments_events_v2
