base:
  serviceName: permissions-ep
  version: develop
  registry: docker-registry.prod.williamhill.plc/platform

  services:
    permission-service:
      enabled: true
      isLocal: false
      replicaCount: 1
      image: permissions-ep
      port: 8080
      network:
        routes:
          - /permissions-ep/