base:
  serviceName: permissions
  version: develop
  registry: docker-registry.prod.williamhill.plc/platform

  services:
    permissions-ep:
      enabled: true
      isLocal: false
      replicaCount: 1
      image: permissions-ep
      port: 8080
      network:
        routes:
          - /permissions-ep/
