environment: usd
namespace: libertonia
host: libertonia.aws-us-east-1.usd.williamhill.plc
hpa:
  enabled: true
minReplicas: 1
maxReplicas: 2
newrelic:
  licenceKey: "" # SSM record doesn't exist, setting to empty string to avoid failures of pipeline
  licenceKeyBase64: "" # SSM record doesn't exist, setting to empty string to avoid failures of pipeline
  insightsKeyBase64: "" # SSM record doesn't exist, setting to empty string to avoid failures of pipeline
permissions:
  values:
    base:
      services:
        permissions-ep:
          enabled: true
