newrelic:
    licenceKeyBase64: ENC[AES256_GCM,data:1dSWgEaXS26ZZ+0PKXFSUsXegWm+J+j7tKzuZoHY4KBKtjhcC4EKdpoU+BRlYKopFbdwRVe7dxA=,iv:+S8kTjvpsWdVdpA/MX0+xY/uR3pjdLAazjsrDMiOFe4=,tag:6pGU8nojTOb0rgHXBvYaHw==,type:str]
    insightsKeyBase64: ENC[AES256_GCM,data:scBq6ESyNW11V3e0Y5DL/VVQ17iClV4oYUHweRqiMtApa8lY21OhBSgxHg/PK67WHcNoFCTzQKsXurabXJ/E9tcciNeIuDNT,iv:jvA8hVxhk6rthbZ7umchr4rJJk7nKGIjOpsH2k1RmJ0=,tag:f+/8XeS0eioMcHsUVQu9Fw==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:440010832978:alias/applications
        created_at: '2022-06-16T21:48:00Z'
        enc: AQICAHjrMqmglORZDNKrcBocvePMjE+2qzgdr/Uia4YLLH8kigGehtHP9GB3vRG9hE58pCb7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvN2ARVBJSQvd5bxUAgEQgDud2oZKc2hb2j0XR8mNp32/Kws+5CRp3FuTshv9NOHmgvv+7b0M1BMjYVzfoUHU80mHjETq+uQYVH1TRQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-06-16T21:48:01Z'
    mac: ENC[AES256_GCM,data:tG4IuWbfIOF0pn6XW8XPnRs2JMOWXlBLdJccUYwFIwWKqdyfPnRfN6bUjuYhm34V4RLJz8uwB216nSC3MT+cVcXSrb5J2oA1sPFer5qXsRbJ69TqmZWvEOKk+DT7niYNlHnjur6XUDYUKVO/2VkokUdxd0RRyi0QiDu437oBfaA=,iv:Pxfos9QbFbcJBcBu/bUqR/WaZySSFRri19t5Vs4s7Eg=,tag:F6qDtKpkjkqxs3Yu9napog==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
